#!/bin/bash

debootstrap \
    --include ncurses-term,python-flask,python-pip,locales,nano,gawk,lsb-release,acl,perl-modules-5.28 \
    --components=main,contrib,extended,non-free 1.7_x86-64 \
    $1 \
    https://dl.astralinux.ru/astra/stable/1.7_x86-64/repository-base
    
    
